name: Build and Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version from git tag
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          # This extracts the version from the tag and removes the leading 'v'

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release -p:Version=$VERSION -p:PackageVersion=$VERSION

      - name: Pack
        run: dotnet pack ./src/CodeArt.ThreadUtils/CodeArt.ThreadUtils.csproj --configuration Release --no-build -p:Version=$VERSION -p:PackageVersion=$VERSION --output ./.nuget

      - name: Push to NuGet
        run: dotnet nuget push ./.nuget/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate